### PR TITLE
Spike sounds

### PR DESCRIPTION
**Pull request by celiasmith**
An update to the raster plot so you can listen to the spikes of neurons you hover over.

### CODE REVIEW

**Comment by tcstewar** [comment]
This really is just so cool.  :)

One UI quesion for people: should this be controlled by mouseover?  Or should you have to click on a row to set that one as the spiking one?  That can make it easier to select something and then, say, move the mouse over to a slider and start moving it up and down and listen to the sounds change.

Also, as it currently stands, it always gives clicks based on the spikes that are being generated *right now*, not what's shown on the right-hand side of the spike raster plot..  So if you rewind time, you'll be hearing spikes from the future.   I think I have a way around that, but I still need to poke at that a bit....  :)

**Comment by celiasmith** [comment]
Good point about clicking on it to 'lock' the neuron being listened too... that would be better, I agree.

**Comment by astoeckel** [comment]
Doesn't work in Firefox. Cannot select rows in the raster plot, which works in Chromium. Probably related to #752 .

Also, playing back audio should use the WebAudio API which is meant for this kind of real-time audio playback, whereas the "Audio" element is for the playback of longer audio files. E.g. the browser will only open one playback stream and mix concurrent events. Am going to have a look at this.

**Comment by astoeckel** [comment]
Implemented the usage of WebAudio, now plays clicks with the actual spike frequency (was much slower on my computer before).

**Comment by tcstewar** [comment]
I just rebased this to master and made some small tweaks to the UI (the width of the selection box, and not having clicks outside the spike area suddenly turn into clicks on mouseover)

**Comment by tcstewar** [comment]
Rebased to master again.  :)

**Comment by tcstewar** [comment]
I just had a sudden inspiration to add a menu option to turn this on and off, so that it's not as surprising when your computer starts making loud clicking sounds (and makes it clearer how to turn it off).  That's a small enough tweak that I'm happy to now merge this into master.  :)

**Pull request merged**
