### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by jgosmann**
This makes the tests run and pass again. It includes a minor fix the the dual-stack IPv6 support with automatically selected ports.

There might be some more changes necessary to get things working on Travis-CI again.

### CODE REVIEW

**Comment by jgosmann** [comment]
I've made some progress with a lot of trial and error, but the tests still fail because the webdriver cannot find the editor (though, locally it works and it is clearly visible on the screenshots).

**Comment by jgosmann** [comment]
I'm giving up on Travis for now, I already sunk way too much time into this. For some reason the webdriver sometimes hangs when retrieving a new URL and I have no idea why.

**Comment by jgosmann** [comment]
I separated the commits to get the tests running locally again into #933. I leave this PR as documentation and starting point for anyone else who wants to take a stab at Travis CI in the future ...

**Comment by astoeckel** [comment]
Can we disable Travis CI then? The constant notifications/GitHub messages regarding "All checks have failed" do not have any semantic value.

**Comment by jgosmann** [comment]
I did disable Travis in the other PR.

**Pull request closed without merging**
