### PR TITLE
Add nengo_mpi and nengo_dl as backend options in gui

### PR DESCRIPTION
**Pull request by leomrocha**
Adding nengo_mpi and nengo_dl as possible backends to be looked for in nengo_gui/exec_env.py

### CODE REVIEW

**Comment by tbekolay** [comment]
The change looks good to me! A few minor process points:

1. We require contributors to sign a [contributor assignment agreement](https://www.nengo.ai/caa.html). To sign it, make a PR adding yourself to [this list](https://github.com/nengo/nengo.github.io/blob/src/people.rst).
2. The first line of the commit message is too long. Please ensure that it conforms to [this template](https://www.nengo.ai/style.html#git).

Thanks!

**Comment by leomrocha** [comment]
PR for contributors list added
Amended commit log

Thx!

**Comment by tcstewar** [comment]
Looks good to me as well!  Thank you @leomrocha for putting this in!

**Comment by leomrocha** [comment]
@tcstewar @tbekolay Thx!
Before this PR I thought about doing something quick more generic for discovery (like checking all modules starting with nengo_ ) but that would be insecure.

**Comment by tcstewar** [comment]
> Before this PR I thought about doing something quick more generic for discovery (like checking all modules starting with nengo_ ) but that would be insecure.

Yup.  The plan is to have a way for installed modules to register themselves (and also be able to do things like register tutorial files that will show up in the GUI), but we haven't had the time to work on that yet.  So this is good for now....

**Comment by tbekolay** [comment]
> a way for installed modules to register themselves

Actually this does exist (see https://github.com/nengo/nengo/pull/1127), but not the tutorial files etc.

**Comment by tcstewar** [comment]
> Actually this does exist (see nengo/nengo#1127),

Ah, right, I'd forgotten that got merged!  I should add that feature in to some of the backends I'm working on, just to try it out....

**Comment by tcstewar** [comment]
This is now merged in to master -- sorry it took forever to happen!  And thank you @leomrocha for doing it!

**Pull request closed without merging**
